# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4b56f1e0f6668c4ed7d21005732be842479e00dda71b09748e8328105c38adec67ce711135d5c4e087362fed02a438e8e74ffed8eb123143972919ed9d81d61

test:
  secret_key_base: 92071392456da5aabb611a3821270de0d505a1da88587cb00e9e306c7517649b185ff5b06a5278f9b8a0a650b66cf275a7be7f4803aa4803927065a587d216c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
